# audio/Fband config
sample_rate: 32000
frame_length: 25  # ms
frame_shift: 10  # ms
mel_bins: 64

# model config
spec_size: 256
patch_size: 4
embed_dim: 96
window_size: 8
latent_channel: 32  # grid
extra_downsample_ratio: 1  # for long audio
num_classes: 0
absolute_position_embedding: False

EC_mlp_ratio: 4
EC_num_head: [ 4, 8, 16, 32 ]
EC_depth: [ 2, 2, 6, 2 ]
EC_attn_norm: True
EC_patch_norm: True
EC_qkv_bias: True
EC_drop_rate: 0.
EC_attn_drop_rate: 0.
EC_drop_path_rate: 0.1

DC_num_head: [32, 16, 8, 4]
DC_depth: [2, 6, 2, 2]
DC_mlp_ratio: 4.
DC_drop_rate: 0.
DC_attn_drop_rate: 0.
DC_drop_path_rate: 0.1
DC_attn_norm: True
DC_patch_norm: True
DC_qkv_bias: True

# training config
pre_training: True
load_encoder: False
load_decoder: False
batch_size: 64
learning_rate: 0.001  # 1e-4 also workable
max_epoch: 100
lr_scheduler: [ 0.02, 0.05, 0.1 ]
lr_scheduler_epoch: [ 4, 5, 6 ]
mask_ratio: 0.6  # grid
norm_pix_loss: True  # grid
restore_mask_only: True  # grid

# paths
data_csv:
  win: workspace\datas.csv
  linux: /home/tlzn/users/zlqiu/datas/zlqiu/Audio_MAE_Base_ST/datas.csv
hdf5_file:  # set empty will not use hdf5
  win: workspace\dataset_pretrain.hdf5
  linux: /home/tlzn/users/zlqiu/datas/zlqiu/Audio_MAE_Base_ST/dataset_pretrain.hdf5
encoder_ckpt:
  win: workspace\2024-06-15_21-16-26\encoder_R1_E1.pth
  linux: ckpt/pretrained/hts_at/HTSAT_ESC_exp=1_fold=1_acc=0.985.pth
decoder_ckpt:
  win: workspace\2024-06-15_21-16-26\decoder_R1_E1.pth
  linux: ckpt/pretrained/hts_at/HTSAT_ESC_exp=1_fold=1_acc=0.985.pth
workspace:
  win: workspace
  linux: workspace

## voice print
#vp_database:
#  win: ckpt\vp\hts_at\model_stopby_train_loss_v0.pkl
#  linux: ../hts_at/ckpt/vp/hts_at/model_stopby_train_loss_v0.pkl
#vp_thrd: 80
#audio_num_per_vp: 10

sys_compatible_keys:
  - data_dir
  - hdf5_file
  - encoder_ckpt
  - decoder_ckpt
  - workspace

